version: '3.7'

services:
  server:
    build:
      context: ./
      target: production-build
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/.env
    restart: 'unless-stopped'
    environment:
      NODE_ENV: development
      PORT: 3000

volumes:
  data:
    driver: local
