version: '3.7'

services:
  server:
    build:
      context: ./
      target: production-build
      dockerfile: Dockerfile
    container_name: mygamelist-backend
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/.env
    restart: 'unless-stopped'
    environment:
      NODE_ENV: development
      PORT: 3000
    networks:
      - backend
    depends_on:
      - redis
    
  redis:
    image: redislabs/redisearch
    container_name: redis
    ports:
      - '6379:6379'
    restart: 'unless-stopped'    
    networks:
      - backend  

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
